### PR TITLE
Pick some less clashing colours and fix first-time-in exception

### PR DESCRIPTION
**Pull request by sevanmarc**
The colours from the start menu palette are a bit less clashing and might change appropriately with the theme. Still not perfect, but at least visible on all the themes I tried!

Also handled a null reference when first running.

### CODE REVIEW

**Comment by yannduran** [comment]
Thanks for doing this Marc. I'm aiming at getting this included in Preview 2.

Thanks for taking the time to look into this for me.

**Comment by sevanmarc** [comment]
Glad to help. I think the underlying problem is that you use more design elements in your start page than MS do in theirs (at least one more level of grouping with the columns), so you have to drag in colours from other theme groups to get the distinction. Not an easy one to solve properly but as you say, they're at least all readable now.

**Comment by yannduran** [comment]
Yes exactly! The other problem is the lack of consistency with their theming.  You know, like in the _Dark_ theme, the _AccentDark_ is actually light, and their _AccentLight_ is actually dark. There's a third one in the middle too, but I don't remember the problem with that one. The accent colors are reasonable in _Dark_ and _Light_, but horrendous in _Blue_.

You have no idea how many hours I spent trying to get the colors to work. In the end I just had to get **something** out as a preview. But I couldn't manage to get past the only 2 out of 3 working.

Thanks again!

Oh btw, are you French?

**Comment by sevanmarc** [comment]
English, with French parents :-)

**Comment by yannduran** [comment]
Ahh, I see. You'd speak the language though surely.

**Comment by sevanmarc** [comment]
You'd think so wouldn't you?! Afraid not though - did the obligatory lessons in school but that was a **very** long time ago now... I've done a fair bit of localisation work (probably because nobody else wants to) so I'm familiar with a lot of language quirks as they relate to software but I don't actually speak any of them.

**Comment by yannduran** [comment]
Oh wow, lol

**Comment by yannduran** [comment]
Preview 2 has been released which includes a fix for this problem.

**Pull request merged**
